# Generated by Django 3.1.5 on 2021-01-27 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.EmailField(default='', max_length=254)),
                ('balance', models.IntegerField(default=0)),
                ('hold', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
