# Generated by Django 3.1.5 on 2021-01-28 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Uuid')),
                ('name', models.TextField(default='', verbose_name='ФИО')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('hold', models.IntegerField(default=0, verbose_name='Холд')),
                ('status', models.BooleanField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
                'ordering': ['-name'],
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
